spring:
  application:
    name: userservice
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres5433:5433/user-service
    username: postgres
    password: postgres

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5433/user-service
    username: postgres
    password: postgres

server:
  port: 8080